### ISSUE TITLE
Add a tooltip in All Ongoing Alerts

### ISSUE THREAD

**Issue by barshathakuri** [IFRCGo/alert-hub-web-app#116]
Additionally, we would like to have an information icon at the side of the "All Ongoing Alerts" title, that when hovered display the following tooltip:

"The IFRC AlertHub shows warnings from authoritative agencies in countries. These warnings have a start time (when the event might happen) and an end time (when it's expected to be over). You'll only see warnings that are happening right now (their start time has already passed) but aren't finished yet (their end time hasn't come yet)."

The exact wording might vary in the next weeks, but this could work as a placeholder.

**Comment by ypyelab** [comment]
Hi team,

I spoke with the team, and they would like to show this tooltip instead:

"The IFRC AlertHub shows current warnings from official alerting agencies. These warnings have a start time (when the event might happen) and an end time (when it's expected to be over). The IFRC Alert Hub shows warnings that are happening right now (their start time has already passed) but aren't finished yet (their end time hasn't come yet)."
